# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190713_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Subject')),
            ],
            options={
                'db_table': 'marks',
                'permissions': (('read_marks', 'Can read marks'),),
            },
        ),
    ]
