# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
