# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190714_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Subject', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set([('subject', 'student')]),
        ),
    ]
